### ISSUE TITLE
Corrupt Layout

### ISSUE THREAD

**Issue by haydenhrm** [bwyap/java-familyfeud#4]
This is the best out of the various projects I've tried. I am having a major issue though, I can't "answer" any questions from the admin board, the question control panel doesn't function right. Am I missing something?
![Screenshot 2021-11-29 204401](https://user-images.githubusercontent.com/10900898/143987101-8e254d55-37ca-4faf-b557-322352ee7935.png)

**Comment by benyap** [comment]
Hey @haydenhrm! Unfortunately I think the corrupted layout might be an issue on Windows for newer versions of Java. I did see this happen on for someone else recently, and they were also on Windows. It's been a long time since I've updated the project - I can assure you this didn't use to happen haha. As far as I know, it still works fine on macOS. 

I don't have time / don't really intend to update this project any further (maybe in the far future, but definitely not any time soon). So the best advice I can offer for now is to try an older version of Java (I haven't tested this, so I'm not sure if this will fix it), or run the program on a macOS device. Sorry if this isn't the ideal outcome!

--

If you (or anyone reading this comment) are a Java programmer and know what the issue is, you are more than welcome to submit a PR to fix the issue :)

**Comment by haydenhrm** [comment]
Thanks @benyap for the response. I know this is a 5 year old project and you're onto other things, so no worries. I will give it a go on my Mac and/or will try to resolve the problems with new JDK version (I finally gave up trying to get the project open in intellij and compiled it okay in eclipse). 

I plan on using your creation to livestream a 'Family Feud' game with a bunch of friends.

Merry Christmas!

**Comment by benyap** [comment]
@haydenhrm ah yes this was made in Eclipse, happy to hear you got it set up. All the best with this and Merry Christmas to you too!

**Comment by dsansone31** [comment]
@haydenhrm Did you have any luck with this? I'm having the same issue and I don't have a Mac alternative.
